# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

docker:
  image: "gcr.io/repo-automation-bots/owlbot-java:latest"

deep-remove-regex:
- "/grpc-google-.*/src"
- "/proto-google-.*/src"
- "/google-.*/src"

deep-preserve-regex:
- "/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/GrafeasUtils.java"
- "/google-cloud-containeranalysis/src/test/java/com/google/cloud/devtools/containeranalysis/v1/ITGrafeasInteropTest.java"
- "/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1/src/main/java/com/google/containeranalysis/v1/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/com/google/containeranalysis/v1beta1/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/attestation/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/build/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/common/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/deployment/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/discovery/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/image/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/pkg/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/provenance/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/ProjectName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/source/UntypedIamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/CVSSv3.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/CVSSv3OrBuilder.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/Cvss.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/IamResourceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/IamResourceNames.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/NoteName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/OccurrenceName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/ScanConfigName.java"
- "/proto-google-cloud-containeranalysis-v1beta1/src/main/java/io/grafeas/v1beta1/vulnerability/UntypedIamResourceName.java"

deep-copy-regex:
- source: "/google/devtools/containeranalysis/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-containeranalysis-$1/src"
- source: "/google/devtools/containeranalysis/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-containeranalysis-$1/src"
- source: "/google/devtools/containeranalysis/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-containeranalysis/src"
